### ISSUE TITLE
The Listing of My Runs is busted in Mobile

### ISSUE THREAD

**Issue by epugh** [o19s/thats-trackable#34]
I think we need to redo the table views using all native Bootstrap, because the formatting is breaking down.  See this screenshot:

![img_2160](https://cloud.githubusercontent.com/assets/22395/8175182/75c1e494-13b4-11e5-986c-97458d1092a8.PNG)

**Comment by Logan-K** [comment]
Mentioned this on flowdock but I'll put it here for a trail too :) I checked out bootstrap tables and I'm a bit hesitant to add those because they scroll. 

Here's a link to an example: http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_table_striped&stacked=h

I personally don't really like this so here is what I've done instead...
![runs_index](https://cloud.githubusercontent.com/assets/7561894/8296692/ccc2839e-1921-11e5-98c0-389b5ffaeaa4.PNG)

I shrunk the buttons to appear better on a mobile screen.

Thoughts?

**Comment by epugh** [comment]
So the buttons are much more useful, but you still can't see anything about what each run is about...   You would have to click on each one individually to understand what is going on.

**Comment by Logan-K** [comment]
Ok round 2. Made the executive decision that the date and training plan are going to be the most important pieces of information on this page so I kept them on the mobile view:
![round_2_runs_index-2](https://cloud.githubusercontent.com/assets/7561894/8345294/d3b7b4f4-1aba-11e5-891d-6ae9220d0b38.PNG)

Thoughts?

**Comment by epugh** [comment]
This is much better....    Is there a more compact "Date" column we could add in that would sneak in the Progress?     Like just do `6-22` or `6-23`?

Also, Instead of Run Information, how about `Options` and then the button just says `Options`.

**Comment by epugh** [comment]
looking forward to PR and wrapping this one up!

**Comment by Logan-K** [comment]
Ok, I've been playing with this view for a bit now and I just don't think there is going to be a way to have the progress included as well. I shrunk the date and everything to try and get it to fit. I don't think it would look readable if it was included:

![more_runs_index](https://cloud.githubusercontent.com/assets/7561894/8369301/5cec138a-1b85-11e5-9189-2292357ee0e7.PNG)

If we shrunk it anymore I just don't think it would be readable
